service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      noStart: true
    seed:
      default:
        sources:
          - table: Clients
            sources: [./dynamodb/seeds/clients.json]


provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: clients/{clientId}

  flights:
    handler: flights/handler.flight
    events:
      - http:
          method: get
          path: flights


resources:
  Resources:
    Clients: ${file(./dynamodb/clients/clients.yml)}
    Policy: ${file(./policies/dynamodb.yml)}


package:
  exclude:
    - dynamodb/seeds/**
    - dynamodb/clients/**
    - policies/**
