service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    start:
      noStart: true
    seed:
      default:
        sources:
          - table: Clients
            sources: [./dynamodb/seeds/clients.json]


provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - 'iot:DescribeEndpoint'
        Resource: "*"
      - Effect: "Allow"
        Action:
          - 'sts:AssumeRole'
        Resource: "*"

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          method: GET
          path: iot/keys
    memorySize: 128
    timeout: 10

  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: clients/{clientId}

  allFlights:
    handler: flights/handler.getAllFlights
    events:
      - http:
          method: get
          path: flights

  geoFlights:
    handler: flights/handler.geoFilteredFlight
    events:
      - http:
          method: get
          path: geofilteredflights

  selectedFlight:
    handler: flights/handler.selectedFlight
    events:
      - http:
          method: get
          path: flights/{icao}

  updateClient:
    handler: handler.updateClient
    logger:
      handler: handler.logger
    events:
      - stream: arn:aws:dynamodb:us-east-1:588567118260:table/Clients/stream/2018-02-01T06:36:42.209

  notifyOthers:
    handler: handler.notifyOthers
    events:
      - stream: arn:aws:dynamodb:us-east-1:588567118260:table/Notifications/stream/2018-02-01T09:10:56.338


resources:
  Resources:
    Clients: ${file(./dynamodb/clients/clients.yml)}
    ClientUpdates: ${file(./dynamodb/clients/clientUpdates.yml)}
    Notifications: ${file(./dynamodb/notifications/notifications.yml)}
    NotificationUser: ${file(./dynamodb/notifications/notificationUser.yml)}
    Policy: ${file(./policies/dynamodb.yml)}


package:
  exclude:
    - dynamodb/seeds/**
    - dynamodb/clients/**
    - policies/**
    - .git/**
    - create-role/**
    - frontend/**
    - iot/**
